-- Removes usage_pings rows generated by Claude's own Playwright test runs
-- against localhost during development on 2026-08-15/16 -- the app's
-- Supabase URL/anon key are hardcoded (lib/supabase.ts), so local/test
-- builds talk to the same live project as production, and UsagePing fires
-- on every page load regardless. These 11 rows are all confirmed dev
-- testing (timestamps line up exactly with that session's test runs, one
-- of them even signed in as a fake test session), not real visitors.
delete from public.usage_pings where created_at < '2026-08-16 00:00:00+00';
